// <auto-generated />
namespace OnlineExamMvcApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class exam145 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(exam145));
        
        string IMigrationMetadata.Id
        {
            get { return "201909110903121_exam145"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
